# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=too-many-lines
# pylint: disable=too-many-statements

# from azure.cli.core.commands import CliCommandType

def load_command_table(self, _):  # pylint: disable=unused-argument
    with self.command_group('logic integration-account'):
        from azext_logic.custom import IntegrationAccountCreate, IntegrationAccountImport
        self.command_table['logic integration-account create'] = IntegrationAccountCreate(loader=self)
        self.command_table['logic integration-account import'] = IntegrationAccountImport(loader=self)

    with self.command_group('logic workflow'):
        from azext_logic.custom import WorkflowCreate, WorkflowUpdate
        self.command_table['logic workflow create'] = WorkflowCreate(loader=self)
        self.command_table['logic workflow update'] = WorkflowUpdate(loader=self)
