# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=too-many-lines
# pylint: disable=too-many-statements
from azext_logic.aaz.latest.logic.integration_account import Create as _IntegrationAccountCreate


class IntegrationAccountImport(_IntegrationAccountCreate):
    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        from azure.cli.core.aaz import AAZFileArg, AAZFreeFormDictArgFormat
        args_schema = super()._build_arguments_schema(*args, **kwargs)
        args_schema.input_path = AAZFileArg(
            options=["--mi-system-assigned"],
            help="Path to a integration account JSON file",
            fmt=AAZFreeFormDictArgFormat()
        )
        args_schema.identity._registered = False
        return args_schema

    def pre_operations(self):
        args = self.ctx.args
        if 'properties' not in args.input_path:
            from azure.cli.core.parser import InvalidArgumentValueError
            raise InvalidArgumentValueError(str(args.input_path) + "does not contain a 'properties' key")

        integration_service_environment = args.input_path['properties'].get(
            'integrationServiceEnvironment', None)
        if integration_service_environment is not None:
            args.integration_service_environment = integration_service_environment



